name: node
version: git
summary: Node.js JavaScript runtime
description: |
  Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine.
  Node.js uses an event-driven, non-blocking I/O model that makes it
  lightweight and efficient. The Node.js package ecosystem, npm, is the
  largest ecosystem of open source libraries in the world.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic

apps:
  node:
    command: usr/local/bin/node
  npm:
    command: usr/local/bin/npm
    aliases: [npm]

parts:
  node:
    source: .
    plugin: autotools
    build-packages: [g++, clang, python]
